In [18]:
# !pip install tensorflow-macos
# !pip install git+https://github.com/TahaAnwar/pafy.git#egg=pafy
# !pip install --upgrade gcloud
# !pip install mediapipe

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow


In [3]:
import tensorflow as tf
import tensorflow_hub as hub
import cv2
from matplotlib import pyplot as plt
import numpy as np
import math 

In [4]:
model = hub.load("/Users/jbell/Desktop/SquashVideoAnalysis/movenet_multipose_lightning_1")
movenet = model.signatures['serving_default']

# Draw Keypoints

In [5]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 3, (0,255,0), -1)

# Draw Edges

In [6]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

# Draw Connections

In [7]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            lines = cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 1)

# Loop Through Person

In [8]:
# Function to loop through each person detected and render
def loop_through_people(frame, keypoints_with_scores, edges, confidence_threshold):
    for person in keypoints_with_scores:
        draw_connections(frame, person, edges, confidence_threshold)
        draw_keypoints(frame, person, confidence_threshold)

In [9]:
# print(keypoints_with_scores[:,])
# person[11]  # Left Hip
# person[12]  # Right Hip
# person[13]  # Left Knee
# person[14]  # Right Knee
# person[15]  # Left Ankle
# person[16]  # Right Ankle

# Make Detections

In [10]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    if ret == True:
        
        # Resize image
        img = frame.copy()
        img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 288,512)
        input_img = tf.cast(img, dtype=tf.int32)
    
        # Detection section
        results = movenet(input_img)
        keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
        print(keypoints_with_scores[:,0])
    
        # Render keypoints 
        loop_through_people(frame, keypoints_with_scores, EDGES, 0.25)
    
        cv2.imshow('Movenet Multipose', frame)
    else:
        break

    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

2023-05-10 21:57:02.328458: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


[[0.22371083 0.18305889 0.07997732]
 [0.4452223  0.6800858  0.06159584]
 [0.0945094  0.66962266 0.05179015]
 [0.3835691  0.76988494 0.08638731]
 [0.81532    0.462158   0.04947201]
 [0.51629895 0.86724806 0.06518994]]
[[1.7123595e-01 2.0440145e-01 1.8423235e-01]
 [4.4162327e-01 7.5894326e-01 4.4878641e-01]
 [4.5214945e-01 5.5259120e-01 5.7532534e-04]
 [4.9315834e-01 6.1279994e-01 3.0354995e-04]
 [4.4068184e-01 7.5758481e-01 3.3381552e-01]
 [4.4068184e-01 7.5758481e-01 3.3381552e-01]]
[[1.7218448e-01 2.0289931e-01 2.8964588e-01]
 [4.4262937e-01 8.2131588e-01 3.8152707e-01]
 [4.4262937e-01 8.2131588e-01 3.8152707e-01]
 [4.5939520e-01 5.3505737e-01 2.1524802e-03]
 [2.9855585e-01 1.6218352e-01 8.1867818e-04]
 [1.7218448e-01 2.0289931e-01 2.8964588e-01]]
[[0.17430523 0.20787206 0.30421585]
 [0.43432847 0.8301889  0.33039558]
 [0.44012246 0.827596   0.15352096]
 [0.43249235 0.5691902  0.00925692]
 [0.17430523 0.20787206 0.30421585]
 [0.50451255 0.83699125 0.1490402 ]]
[[0.16951792 0.20279932 

In [11]:
def calculate_distance(frame, keypoints):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    lst.append(shaped[0])
    try:
#             print(keypoints_with_scores[:,0,0][i] - keypoints_with_scores[:,0,0][i - 1])
#     except:
#         pass
#     print("----")
#     for i in range(len(keypoints_with_scores[:,0,0])):
#         print(keypoints_with_scores[:,0,0][i])
    print(lst)
#     print(keypoints[0])
#     print(shaped[0])

IndentationError: expected an indented block after 'try' statement on line 6 (2354694882.py, line 13)

# Class for Person

In [87]:
class Person:
    def __init__(self, prev_x = 0, prev_y = 0, curr_x = 0, curr_y = 0, conf = 0):
        self.prev_x = prev_x
        self.prev_y = prev_y
        self.curr_x = curr_x
        self.curr_y = curr_y
        self.conf = conf
        self.distance = 0
        
    
    def draw_keypoints(self, frame, keypoints, confidence_threshold):
        y, x, c = frame.shape
        shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
        
        for kp in shaped:
            ky, kx, kp_conf = kp
            if kp_conf > confidence_threshold:
                cv2.circle(frame, (int(kx), int(ky)), 3, (0,255,0), -1)
#             print("kx: ", kx)
         
    def draw_connections(self, frame, keypoints, edges, confidence_threshold):
        y, x, c = frame.shape
        shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))

        for edge, color in edges.items():
            p1, p2 = edge
            y1, x1, c1 = shaped[p1]
            y2, x2, c2 = shaped[p2]

            if (c1 > confidence_threshold) & (c2 > confidence_threshold):
                    lines = cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 1)
                
    def calculate_distance(self, frame, keypoints, confidence_threshold):
        y, x, c = frame.shape
        shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
        
        for kp in shaped:
            ky, kx, kp_conf = kp
            self.conf = kp_conf
            
            if self.prev_x == 0:
                self.prev_x = kx
                self.prev_y = ky
            else:
                self.curr_x = kx
                self.curr_y = ky
            
                # calculate distance

                if kp_conf >= confidence_threshold:
                    try:
                        d_sqr = (self.curr_x - self.prev_x)**2 + (self.curr_y - self.prev_y)**2
                        self.distance += math.sqrt(d_sqr)
                    except:
                        pass
                self.prev_x = self.curr_x
                self.prev_y = self.curr_y
                
#             cv2.putText(frame, str('HERE'), (int(self.curr_x),int(self.curr_y)), cv2.FONT_HERSHEY_DUPLEX, 1, (255, 0, 0), 1)

    def put_text(self, image, confidence_threshold):
        if self.
            try:
    #             cv2.putText(frame, str(self.distance), (int(shaped[16][1]), int(shaped[16][0])), cv2.FONT_HERSHEY_DUPLEX, 1, (255, 0, 0), 1)
                cv2.putText(image, str(self.distance), (int(self.curr_x), int(self.curr_y)), cv2.FONT_HERSHEY_DUPLEX, 1, (255, 0, 0), 2)
    #                 cv2.putText(image, str(self.distance), (int(self.curr_x), int(self.curr_y)), cv2.FONT_HERSHEY_DUPLEX, 1, (255, 0, 0), 2)
            except:
                pass

# Run Camera Detections

In [88]:
per = Person()
cap = cv2.VideoCapture('watermarked_preview.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    if ret == True:
        
        # Resize image
        img = frame.copy()
        img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 288,512)
        input_img = tf.cast(img, dtype=tf.int32)
    
        # Detection section
        results = movenet(input_img)
        keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
    
        # Render keypoints 
        for person in keypoints_with_scores:
            per.draw_keypoints(frame, person, 0.05)
            per.draw_connections(frame, person, EDGES, 0.05)
            per.calculate_distance(frame, person, .6)
            per.put_text(frame, .6)
    
        cv2.imshow('Movenet Multipose', frame)
    else:
        break

    if cv2.waitKey(1) & 0xFF==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


In [65]:
class Test:   
    def __init__(self, distance, ylst = [], xlst = []):
        self.distance = distance
        self.xlst = xlst
        self.ylst = ylst
        
    def calculate_distance(self, a, b):
        self.distance = a + 1
#         self.xlst.append(a)
        return self.distance, self.xlst

ex = Test(0)

# print(ex.xlst)
ex.calculate_distance(2, 7)
ex.distance

3